version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=OrderlyHub.settings
      - POSTGRES_DB=my_database_name
      - POSTGRES_USER=my_username
      - POSTGRES_PASSWORD=my_password

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_database_name
      POSTGRES_USER: my_username
      POSTGRES_PASSWORD: my_password