# Generated by Django 5.1.dev20240412151528 on 2024-04-15 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0004_remove_order_items_remove_orderitem_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_without_tax',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(default=None, through='orders.OrderItem', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price_with_taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price_without_taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
