# Generated by Django 5.1.dev20240412151528 on 2024-04-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_id_alter_order_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price_with_taxes',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
